#!/usr/bin/python3
#
# Author:   Kalvin
#
# Usage:    python3 ./ltdz_log2_table.py
#
# Generates log2 lookup-table C include-file ltdz_log2_table.inc.
#

import os
import math

THISFILE = os.path.basename(__file__)

# Output file name
OUTFILE = "ltdz_log2_table.inc"

# Log2 table size
TABLE_SIZE = 256

print("Generating log2 lookup-table C include file {}".format(OUTFILE))

sep = ","
with open(OUTFILE, 'w') as f:
    f.write("/**\n")
    f.write(" * Do not edit or modify manually.\n")
    f.write(" * Generated by python script file {}\n".format(THISFILE))
    f.write(" */\n")
    for n in range(0, TABLE_SIZE):
        man = round(math.log2(1.0 + n/TABLE_SIZE)*100.0)
        if n == TABLE_SIZE-1:
            sep = ""
        f.write("/* {:3} */ {}{}\n".format(n, man, sep))
    f.write("/* end of file */\n")

print("Done.")
